name: Run GUT Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test-action:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:latest
    services:
      gsx2jsonpp:
        image: deflinhec/gsx2jsonpp:latest
        env:
          ARGUMENTS: --host=0.0.0.0 --port=5000
        ports:
          - 5000:5000
        volumes: 
          - /volume:/workspace
        options: >-
          --name gsx2jsonpp
          --health-cmd "nc -z localhost 5000"
          --health-interval 10s 
          --health-timeout 10s 
          --health-retries 6 
          --health-start-period 60s
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure hostname
      run: >-
        sed -i 's/localhost/gsx2jsonpp/g' \
        test/unit/test_google_sheet.gd
    - name: Run Action
      uses: josephbmanley/run-gut-tests-action@v1.1.0
      with:
        useContainer: false 
