name: Run GUT Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: Start Gsx2jsonpp
      run: >-
        /usr/bin/docker run -itd 
        -e ARGUMENTS="--host=0.0.0.0 --port=5000" 
        -p 5000:5000 -v /volume:/workspace 
        --name gsx2jsonpp deflinhec/gsx2jsonpp:latest 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Action
      uses: josephbmanley/run-gut-tests-action@v1.0.1
