name: Run GUT Tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test-action:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:latest
    services:
      gsx2json-go:
        image: deflinhec/gsx2json-go:latest
        options: >-
          --name gsx2json-go
          --health-cmd "nc -z localhost 8080"
          --health-interval 10s 
          --health-timeout 10s 
          --health-retries 6 
          --health-start-period 60s
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure hostname
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "localhost"
        replace: "gsx2json-go"
        include: "test/unit/test_google_sheet.gd"
    - name: Configure google api key
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "YOUR_GOOGLE_SHEET_API_KEY"
        replace: ${{ secrets.GOOGLE_SHEET_API_KEY }}
        include: "test/unit/test_google_sheet.gd"
    - name: Run Action
      uses: josephbmanley/run-gut-tests-action@v1.1.0
      with:
        useContainer: false 
